apiVersion: v1
kind: Service
metadata:
  name: wilapp-service
spec:
  type: ClusterIP
  selector:
    app: wilapp
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilapp-deployment
  labels:
    app: wilapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wilapp
  template:
    metadata:
      labels:
        app: wilapp
    spec:
      containers:
      - name: wilapp
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
